name: DetoxPantry
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1704322414007038
title: 'DetoxPantry.com | Sensible Detox & Wellness'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3fe0a'
    - '#090909'
    - '#ef6b04'
    - '#3ca804'
    - '#d10e03'
  brandStrength: 0.18780664866790175
  lightness: 0.811504557961598
  saturation: 0.4624893425498158
  rhythmicContrast: 0.09840630856342614
purpose: []
